version: '3.9'
# If using colima as docker runtime on osx, then set WORKDIR so volume mounts work.
# WORKDIR=`pwd` docker-compose up
services:
  postgres:
    build:
      context: .
      dockerfile: pg.Dockerfile
    volumes:
      - ${PWD}/crowd.sql:/docker-entrypoint-initdb.d/crowd.sql
      - ${PWD}/postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-example}
#    ports:
#      - 5432:5432

  cube_api:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_LOG_LEVEL=info
      - DEBUG_LOG=true
      - CUBEJS_DB_HOST=postgres
      - CUBEJS_DB_USER=postgres
      - CUBEJS_DB_NAME=${POSTGRES_DB:-example}
      - CUBEJS_DB_PASS=${POSTGRES_PASSWORD:-postgres}
      - CUBEJS_DB_PORT=5432
      - CUBEJS_API_SECRET=secret1234
      - CUBEJS_DB_TYPE=postgres
      # - CUBEJS_EXTERNAL_DEFAULT=true
      - CUBEJS_SCHEDULED_REFRESH_DEFAULT=true
      - CUBEJS_DEV_MODE=true
      - CUBEJS_PG_SQL_PORT=5432
      - CUBEJS_SQL_USER=myusername
      - CUBEJS_SQL_PASSWORD=mypassword
    volumes:
      - ${PWD}:/cube/conf
      - ${PWD}/schema:/cube/schema
    depends_on:
      - postgres