name: Test

on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main

env:
  CUBEJS_DS_REDSHIFTLFX_DB_HOST: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_HOST}}
  CUBEJS_DS_REDSHIFTLFX_DB_PORT: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_PORT}}
  CUBEJS_DS_REDSHIFTLFX_DB_NAME: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_NAME}}
  CUBEJS_DS_REDSHIFTLFX_DB_USER: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_USER}}
  CUBEJS_DS_REDSHIFTLFX_DB_PASS: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_PASS}}
  CUBEJS_DS_REDSHIFTLFX_DB_TYPE: ${{secrets.CUBEJS_DS_REDSHIFTLFX_DB_TYPE}}

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run schema compile check
      run: yarn validate
    - name: Run tests
      run: yarn test
    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down

   